FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY target/product-service-1.0.0.jar app.jar
EXPOSE 8081
CMD ["java", "-jar", "app.jar"]                                                                                                                                                        
                                  
